import React, { useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { toast } from 'react-hot-toast';
import { SparklesIcon, RocketLaunchIcon, GlobeAltIcon } from '@heroicons/react/24/outline';

export default function Home() {
  const router = useRouter();
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState('');

  const handleGenerateWebsite = async () => {
    if (!prompt.trim()) {
      toast.error('Please enter a description for your website');
      return;
    }

    setIsLoading(true);
    
    try {
      const response = await fetch('/api/generate/website', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: prompt.trim(),
          context: {
            websiteType: selectedTemplate || 'business',
            tone: 'professional',
            style: 'modern',
          },
        }),
      });

      const result = await response.json();

      if (result.success) {
        // Store the generated website data
        localStorage.setItem('generatedWebsite', JSON.stringify(result.data));
        
        // Navigate to the editor
        router.push('/editor');
        
        toast.success('Website generated successfully!');
      } else {
        toast.error(result.error || 'Failed to generate website');
      }
    } catch (error) {
      console.error('Generation error:', error);
      toast.error('An error occurred while generating your website');
    } finally {
      setIsLoading(false);
    }
  };

  const templates = [
    { id: 'business', name: 'Business', icon: '🏢' },
    { id: 'portfolio', name: 'Portfolio', icon: '🎨' },
    { id: 'landing', name: 'Landing Page', icon: '🚀' },
    { id: 'blog', name: 'Blog', icon: '📝' },
    { id: 'ecommerce', name: 'E-commerce', icon: '🛒' },
    { id: 'restaurant', name: 'Restaurant', icon: '🍽️' },
    { id: 'agency', name: 'Agency', icon: '💼' },
    { id: 'health', name: 'Health & Fitness', icon: '🏥' },
  ];

  return (
    <>
      <Head>
        <title>AI Website Builder - Create Stunning Websites in Minutes</title>
        <meta name="description" content="Create professional websites with AI. Just describe your business and get a complete website with content, images, and responsive design." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
        {/* Header */}
        <header className="border-b border-gray-200 bg-white/80 backdrop-blur-sm">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center py-4">
              <div className="flex items-center space-x-2">
                <SparklesIcon className="h-8 w-8 text-blue-600" />
                <span className="text-xl font-bold text-gray-900">AI Website Builder</span>
              </div>
              <nav className="hidden md:flex space-x-8">
                <a href="#features" className="text-gray-600 hover:text-blue-600 transition-colors">Features</a>
                <a href="#templates" className="text-gray-600 hover:text-blue-600 transition-colors">Templates</a>
                <a href="#pricing" className="text-gray-600 hover:text-blue-600 transition-colors">Pricing</a>
              </nav>
            </div>
          </div>
        </header>

        {/* Hero Section */}
        <section className="py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              Create Stunning Websites with{' '}
              <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                AI Power
              </span>
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
              Just describe your business and get a complete website with content, images, and responsive design - all generated by AI in minutes.
            </p>

            {/* Website Generation Form */}
            <div className="bg-white rounded-2xl shadow-xl p-8 mb-12">
              <h2 className="text-2xl font-semibold mb-6 text-gray-900">
                What kind of website do you want to create?
              </h2>
              
              {/* Template Selection */}
              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-3">
                  Choose a template type (optional)
                </label>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  {templates.map((template) => (
                    <button
                      key={template.id}
                      onClick={() => setSelectedTemplate(template.id)}
                      className={`p-3 rounded-lg border-2 transition-all ${
                        selectedTemplate === template.id
                          ? 'border-blue-500 bg-blue-50 text-blue-700'
                          : 'border-gray-200 hover:border-gray-300 text-gray-700'
                      }`}
                    >
                      <div className="text-2xl mb-1">{template.icon}</div>
                      <div className="text-sm font-medium">{template.name}</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Prompt Input */}
              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-3">
                  Describe your website
                </label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="e.g., A modern fitness studio in downtown offering yoga classes, personal training, and nutrition coaching. We focus on holistic wellness and building a supportive community."
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                  rows={4}
                />
              </div>

              {/* Generate Button */}
              <button
                onClick={handleGenerateWebsite}
                disabled={isLoading || !prompt.trim()}
                className="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold py-4 px-8 rounded-lg hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center justify-center space-x-2"
              >
                {isLoading ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                    <span>Generating your website...</span>
                  </>
                ) : (
                  <>
                    <RocketLaunchIcon className="h-5 w-5" />
                    <span>Generate My Website</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-20 px-4 sm:px-6 lg:px-8 bg-white">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
                Everything You Need to Build Amazing Websites
              </h2>
              <p className="text-xl text-gray-600">
                Powered by advanced AI technology to create professional websites in minutes
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
              <div className="text-center p-6">
                <div className="bg-blue-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                  <SparklesIcon className="h-8 w-8 text-blue-600" />
                </div>
                <h3 className="text-xl font-semibold mb-2">AI-Powered Generation</h3>
                <p className="text-gray-600">
                  Our AI creates complete websites with content, images, and design tailored to your business
                </p>
              </div>

              <div className="text-center p-6">
                <div className="bg-green-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                  <GlobeAltIcon className="h-8 w-8 text-green-600" />
                </div>
                <h3 className="text-xl font-semibold mb-2">Responsive Design</h3>
                <p className="text-gray-600">
                  All websites are automatically optimized for desktop, tablet, and mobile devices
                </p>
              </div>

              <div className="text-center p-6">
                <div className="bg-purple-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                  <RocketLaunchIcon className="h-8 w-8 text-purple-600" />
                </div>
                <h3 className="text-xl font-semibold mb-2">One-Click Deploy</h3>
                <p className="text-gray-600">
                  Launch your website instantly with our hosting or export to use anywhere
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Templates Preview */}
        <section id="templates" className="py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
                Choose from Various Template Types
              </h2>
              <p className="text-xl text-gray-600">
                Our AI adapts to create the perfect website for your specific industry and needs
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              {templates.map((template) => (
                <div key={template.id} className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow">
                  <div className="text-4xl mb-4">{template.icon}</div>
                  <h3 className="text-lg font-semibold mb-2">{template.name}</h3>
                  <p className="text-gray-600 text-sm">
                    Perfect for {template.name.toLowerCase()} websites with all the essential features
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-r from-blue-600 to-purple-600">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Ready to Create Your Website?
            </h2>
            <p className="text-xl text-blue-100 mb-8">
              Join thousands of users who have already created amazing websites with our AI
            </p>
            <button
              onClick={() => document.querySelector('textarea')?.focus()}
              className="bg-white text-blue-600 font-semibold py-4 px-8 rounded-lg hover:bg-gray-100 transition-colors"
            >
              Start Building Now
            </button>
          </div>
        </section>

        {/* Footer */}
        <footer className="bg-gray-900 text-white py-12 px-4 sm:px-6 lg:px-8">
          <div className="max-w-6xl mx-auto text-center">
            <div className="flex items-center justify-center space-x-2 mb-4">
              <SparklesIcon className="h-6 w-6 text-blue-400" />
              <span className="text-lg font-semibold">AI Website Builder</span>
            </div>
            <p className="text-gray-400">
              Create professional websites with the power of AI. Fast, easy, and beautiful.
            </p>
          </div>
        </footer>
      </div>
    </>
  );
}